language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"


cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
addons:
  apt:
    packages:
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy=1.9.0 scipy=0.16.0 nose scikit-learn=0.16.1 Cython pandas
  - pip install mock --no-deps
  - pip install lockfile==0.10.2 --no-deps
  - pip install pep8 python-coveralls
  - pip install coverage

  # Install requirements from other repos
  - pip install git+https://github.com/automl/HPOlibConfigSpace.git
  - pip install git+https://github.com/automl/paramsklearn.git

script:
  - coverage run --source autosklearn setup.py test

after_success: coveralls