language: python

sudo: false

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
  pip: true

# command to install dependencies
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

env:
  global:
  # Directory where tests are run from
  - TEST_DIR=/tmp/test_dir/
  - MODULE=autosklearn
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.4"
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

install:
  # Necessary for random forest
  - export CXX="g++-4.8" CC="gcc-4.8"
  - source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh

