language: python
python:
  - "2.7"
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

before_install:
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy>=0.16.0 scipy>=0.14.0 setuptools nose ConfigArgParse liac-arff lockfile
  - source activate test-environment

  # Install requirements from other repos
  - pip install git+https://github.com/automl/HPOlibConfigSpace.git
  - pip install git+https://github.com/automl/paramsklearn.git

  - python setup.py install

  #- easy_install -U distribute
  #- pip install numpy>=0.16.0
  #- pip install scipy>=0.14.0
  #- python setup.py install

# command to run tests, e.g. python setup.py test
script:  python setup.py test