language: python

sudo: false

os:
  - linux
  - osx

matrix:
  allow_failures:
  - os: osx
  
  include:
  - os: linux
    DISTRIB="conda" PYTHON_VERSION="3.4"
  - os: linux
    DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

  # Set language to generic to not break travis-ci
  # https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855
  # so far, this issue is still open and there is no good solution
  # python will then be installed by anaconda
  - os: osx
    sudo: required
    language: generic
    DISTRIB="conda" PYTHON_VERSION="3.4"
  - os: osx
    sudo: required
    language: genericDISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

cache:
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
  pip: true

env:
  global:
  # Directory where tests are run from
  - TEST_DIR=/tmp/test_dir/
  - MODULE=autosklearn

install:
  # Necessary for random forest
  #- export CXX="g++-4.8" CC="gcc-4.8"
  - source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh

