language: python
python:
  - "2.7"
  - "3.4"

cache: pip
cache:
  directories:
    - $HOME/.cache/pip

sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

#before_install:
  #- sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran

install:
  - easy_install -U distribute
  - pip install numpy>=0.16.0
  - pip install scipy>=0.14.0

  # Install requirements from other repos
  - pip install git+https://github.com/automl/HPOlibConfigSpace.git
  - pip install git+https://github.com/automl/paramsklearn.git

  - python setup.py install

# command to run tests, e.g. python setup.py test
script:  python setup.py test